### PR TITLE
Update hyper and serde_json

### PR DESCRIPTION
**Pull request by sb89**
Updated hyper to 0.10 and serde_json to 1.0.

### CODE REVIEW

**Comment by sb89** [comment]
Instead of using hyper, would it be better to use reqwest?

**Comment by matthew-piziak** [comment]
Thank you @sb89. 

@zeyla I have removed `darksky` from my application pending the merge of this PR (OpenSSL conflicts). Could you please merge it?

**Comment by zeyla** [comment]
Thanks for the PR @sb89, and thanks for the re-ping @matthew-piziak!

Sorry I didn't get to this sooner, I saw it when it was opened but got carried away with work. It's unfortunate GitHub doesn't have a better dashboard to handle open PRs and issues.

I think `reqwest` is a bit more than what `darksky` needs; `hyper` + `hyper-native-tls` should get the job done for what we need.

I also apologize for this repo being a bit behind on, well, everything, and generally being dead. I've got a list down of things I wanted to do sometime, but other things just kept coming up. I'll take some time this evening to bring this library up-to-date and release a new version.

**Comment by matthew-piziak** [comment]
No worries @zeyla, we're all grateful for your efforts. :) Looking forward
to the next release!

**Pull request merged**
